spring:
  application:
    name: "Projeto SAP Academia Commerce"

  datasource:
    url: jdbc:mysql://localhost:3306/cursos?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abc12345

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
